ARG python_version
FROM elifesciences/python_3.6_pipenv:${python_version}

# force latest pipenv, should be upgraded in base image
RUN pip install --upgrade pipenv

ARG pipenv_dev_arg

ENV PROJECT_FOLDER=/srv/profiles
WORKDIR ${PROJECT_FOLDER}

RUN virtualenv venv
ENV VIRTUAL_ENV=${PROJECT_FOLDER}/venv

COPY Pipfile Pipfile.lock ./
RUN pipenv sync ${pipenv_dev_arg}
