FROM elifesciences/python:b22fbad8f66100d88cb4bd7c7d092b376a9e09bc

ENV PROJECT_FOLDER=/srv/profiles
WORKDIR ${PROJECT_FOLDER}

USER root
RUN chown --recursive elife:elife .

USER elife

RUN virtualenv venv

COPY requirements.txt ./
RUN venv/bin/pip install --requirement requirements.txt --no-cache-dir
