ARG commit=develop
FROM elifesciences/profiles:${commit}
ENV DEBUG=1

USER elife
RUN pipenv install --deploy --dev
COPY --chown=elife:elife test/ /srv/profiles/test/
COPY --chown=elife:elife \
    .coveragerc \
    .flake8 \
    project_tests.sh \
    .pylintrc \
    pytest.ini \
    /srv/profiles/
RUN mkdir build/ && chmod 777 build/

USER www-data
CMD ["/bin/bash"]
