version: '3'

services:
    venv:
        build:
            args:
                pipenv_dev_arg:
    venv-dev:
        build:
            context: .
            dockerfile: Dockerfile.venv
            args:
                pipenv_dev_arg: --dev
                python_version: ${PYTHON_VERSION}
        image: elifesciences/profiles_venv_dev:${IMAGE_TAG}
    wsgi:
        build:
            args:
                dependencies_orcid_dummy: "${DEPENDENCIES_ORCID_DUMMY}"
        command: venv/bin/uwsgi --ini=/srv/profiles/uwsgi.ini
    db:
        image: postgres:9.4
        volumes:
            - ./config/application_user.sql:/docker-entrypoint-initdb.d/application_user.sql
        env_file:
            - dev.env
    ci:
        build: 
            context: .
            dockerfile: Dockerfile.ci
            args:
                image_tag: "${IMAGE_TAG}"
        image: elifesciences/profiles_ci:${IMAGE_TAG}
        env_file:
            - dev.env
        environment:
            - COVERALLS_REPO_TOKEN
        depends_on:
            - venv-dev
