version: '3'

services:
    web:
        image: nginx:1.13.7
        ports:
            - "8080:80"
        volumes:
            - ./config/nginx-default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - wsgi
    wsgi:
        build: 
            context: .
            dockerfile: Dockerfile.wsgi
        image: elifesciences/profiles_wsgi
        volumes:
            # TODO: this can't be done as it will overwrite the venv/
            #- ./:/srv/profiles
            - ./config/app.cfg:/srv/profiles/app.cfg
            - ./config/clients.yaml:/srv/profiles/clients.yaml
            - ./config/uwsgi.ini:/srv/profiles/uwsgi.ini
            - logs:/srv/profiles/var/logs
        env_file:
            - dev.env

volumes:
    logs:
